FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libgtk-3-dev libasound2-dev libpulse-dev libjack-dev

ADD . /repo
WORKDIR /repo
RUN cp /repo/makefiles/makefile.defs.linux.barren /repo/makefile.defs
RUN make -j8
